- name: PLAY-1
  hosts: ansible_agent
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello I am from PLAY-1 and TASK-1"

- name: PLAY-2
  hosts: ansible_agent
  tasks:
  - name: PLAY-2 and TASK-1
    ansible.builtin.debug:
       msg: "Hello I am from PALY-2 and TASK-1"